// declaration for constant
export const FETCHING_SOURCES = "FETCHING_SOURCES";
export const FETCH_SOURCES_FULFILLED = "FETCH_SOURCES_FULFILLED";
export const FETCH_SOURCES_REJECTED = "FETCH_SOURCES_REJECTED";
export const FETCH_SOURCES_CATEGORY = "FETCH_SOURCES_CATEGORY";
export const  FETCHING_ARTICLES = "FETCHING_ARTICLES";
export const FETCH_ARTICLES_FULFILLED = "FETCH_ARTICLES_FULFILLED";
export const FETCH_ARTICLES_REJECTED = "FETCH_ARTICLES_REJECTED";
export const SET_VISIBILITY_FILTER = "SET_VISIBILITY_FILTER";

