// declaration for constant
export const FETCHING_SOURCES = "FETCHING_SOURCES";
export const FETCH_SOURCES_FULFILLED = "FETCH_SOURCES_FULFILLED";
export const FETCH_SOURCES_REJECTED = "FETCH_SOURCES_REJECTED";
export const FETCH_SOURCES_CATEGORY = "FETCH_SOURCES_CATEGORY";
